apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: techstore-app
  labels:
    app: techstore
type: Opaque
data:
  POSTGRES_DB: dGVjaHN0b3JlZGI=          # techstoredb
  POSTGRES_USER: YWRtaW50ZWNoc3RvcmU=      # admintechstore
  POSTGRES_PASSWORD: VGVjaFN0b3JlMjAyNEAh  # TechStore2024@!
