apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: techstore-app
  labels:
    app: techstore
    tier: frontend
spec:
  type: NodePort
  selector:
    app: techstore
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
